= Personal Backups
Ryan Schuetzler <rschuetzler@unomaha.edu>
v0.1 2018-05-02

Today's students store more of their valuable data digitally than ever before.
For school, assignments, research papers, lab data, class notes, and many other important files are stored on computers.
Many people have other personal files as well: photos, tax records, valuable messages, or other things.
These files are too important to be stored only in one place.
To protect them from disaster and catastrophe, backups are critical.

Too often we see that devices fail at the worst possible time.
A hard drive crashes the last week of the semester and a month-long graduate research project is lost.
A phone is stolen, and precious photos of young children are lost forever.
A laptop is dropped on the ground, and several years of assignments, notes, and a portfolio are lost.

Bad things can happen to anyone at any time.
Data loss can happen to individuals or to large companies, and having a good backup strategy is just as important in both cases.
Below are a few examples of times when backups could have saved the day:

* https://thenextweb.com/media/2012/05/21/how-pixars-toy-story-2-was-deleted-twice-once-by-technology-and-again-for-its-own-good/[Pixar's Toy Story 2 was accidentally deleted from their servers, and almost lost].
* DJ Skrillex https://www.altpress.com/news/entry/skrillex_sonny_moore_has_laptops_stolen_containing_new_album/[had a laptop stolen that contained the only copy of his yet-to-be-released album].
* A rapper http://newsfeed.time.com/2013/01/05/rapper-ryan-leslie-ordered-to-pay-1-2-million-reward-for-lost-laptop/[paid a $1.2 million reward for a lost laptop].
* A graduate student in Calgary, Alberta https://calgary.ctvnews.ca/stolen-laptop-contains-man-s-dreams-1.546352[had his laptop and backup hard drive stolen from his car, losing years of work toward a dissertation].

== The 3-2-1 Rule

== Backup vs. Cloud Sync
